language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r web1 *
  - mkdir -p deploy
  - mv web1.zip deploy/web1.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yappian
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: yapp-project/yappian-server
      branch: master
  
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yappian
    key: web1.zip
    bundle_type: zip
    application: yappian
    deployment_group: yappian-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: yapp-project/yappian-server
      branch: master

notifications:
  email:
    recipients:
      - kdkyung57@gmail.com 